function Hd = getFilter2
%GETFILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 24-Nov-2018 12:57:59

Fpass1 = 0.068;  % First Passband Frequency
Fstop1 = 0.07;   % First Stopband Frequency
Fstop2 = 0.073;  % Second Stopband Frequency
Fpass2 = 0.075;  % Second Passband Frequency
Apass1 = 1;      % First Passband Ripple (dB)
Astop  = 60;     % Stopband Attenuation (dB)
Apass2 = 1;      % Second Passband Ripple (dB)

h = fdesign.bandstop('fp1,fst1,fst2,fp2,ap1,ast,ap2', Fpass1, Fstop1, ...
    Fstop2, Fpass2, Apass1, Astop, Apass2);

Hd = design(h, 'equiripple');


